# compose.yaml
#gotta setup this
services:
  datacollector:
    build:
      context: ./datacollector
      dockerfile: dockerfile
    depends_on:
      - influxdb2
    hostname: datacollector
    environment:
      USERNAME_HASH_SECRET_FILE: /run/secrets/username-hash-secret
      MACHINE_NAME: Happyrobot33-PC
    secrets:
      - username-hash-secret
    #bind the vrchat log folder
    volumes:
      - type: bind
        source: C:\Users\Matthew\AppData\LocalLow\VRChat\VRChat #change to your vrchat log folder
        target: /logs
        read_only: true
  influxdb2:
    image: influxdb:2
    hostname: influxdb2
    ports:
      - 8086:8086
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME_FILE: /run/secrets/influxdb2-admin-username
      DOCKER_INFLUXDB_INIT_PASSWORD_FILE: /run/secrets/influxdb2-admin-password
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN_FILE: /run/secrets/influxdb2-admin-token
      DOCKER_INFLUXDB_INIT_ORG: org
      #DOCKER_INFLUXDB_INIT_BUCKET: collected-data #no initial bucket, we make a bucket per world id
    volumes:
      - type: volume
        source: influxdb2-data
        target: /var/lib/influxdb2
      - type: volume
        source: influxdb2-config
        target: /etc/influxdb2
    secrets:
      - influxdb2-admin-username
      - influxdb2-admin-password
      - influxdb2-admin-token
volumes:
  influxdb2-data:
  influxdb2-config:
secrets:
  username-hash-secret:
    file: secrets/.env.username-hash-secret
  influxdb2-admin-username:
    file: secrets/.env.influxdb2-admin-username
  influxdb2-admin-password:
    file: secrets/.env.influxdb2-admin-password
  influxdb2-admin-token:
    file: secrets/.env.influxdb2-admin-token
